export const PENALTY_OPTIONS = [
  { code: "HOOK", label: "Hooking" },
  { code: "HOLD", label: "Holding" },
  { code: "TRIP", label: "Tripping" },
  { code: "INT", label: "Interference" },
  { code: "SLASH", label: "Slashing" },
  { code: "HI-ST", label: "High-Sticking" },
  { code: "CROSS", label: "Cross-Checking" },
  { code: "ROUGH", label: "Roughing" },
  { code: "ELBOW", label: "Elbowing" },
  { code: "KNEE", label: "Kneeing" },
  { code: "DEL", label: "Delay of Game" },
  { code: "TMM", label: "Too Many Men" },
  { code: "HLD-ST", label: "Holding the Stick" },
  { code: "USC", label: "Unsportsmanlike Conduct" },
  { code: "G-INT", label: "Goalie Interference" },
  { code: "DIVE", label: "Embellishment/Diving" },
  { code: "POG", label: "Puck Over the Glass" },
  { code: "HI-ST+", label: "High-Sticking (Blood)" },
  { code: "SPEAR", label: "Spearing (Minor)" },
  { code: "FIGHT", label: "Fighting" },
  { code: "BOARD", label: "Boarding" },
  { code: "CHARG", label: "Charging" },
  { code: "CFB", label: "Checking from Behind" },
  { code: "SPEAR+", label: "Spearing (Major)" },
  { code: "BUTT", label: "Butt-Ending" },
  { code: "H-BUT", label: "Head-Butting" },
  { code: "CLIP", label: "Clipping" },
  { code: "MISC", label: "Misconduct" },
  { code: "GM", label: "Game Misconduct" },
  { code: "MATCH", label: "Match Penalty" },
  { code: "GMISC", label: "Gross Misconduct" },
  { code: "G-PUCK", label: "Handling the Puck" },
  { code: "G-COV", label: "Covering the Puck" },
  { code: "G-CRES", label: "Leaving the Crease" },
] as const;
